apiVersion: v1
kind: Pod
metadata:
  name: pod-as-user
  namespace: pong
spec:
  containers:
  - name: ping
    image: alpine
    securityContext:
      runAsUser: 1000
    command:
    - sleep
    - "5000"

