apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pong
generatorOptions:
  disableNameSuffixHash: true # Wird eigentlich hier nicht gebraucht sondern, wenn eine spezielle Configmap erstellt wird
  annotations:
    iwas: here
configMapGenerator:
- name: djay-cm
  files:
  - index.html
resources:
- namespaces_pong.yaml
- pong.yaml
